#############################################################################
# Makefile for building: beleg
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mo. Jun 25 17:56:30 2018
# Project:  beleg.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile beleg.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/default -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -L/usr/lib64 -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		medium.cpp \
		book.cpp \
		cd.cpp \
		dvd.cpp \
		person.cpp \
		addnewperson.cpp \
		datamanager.cpp \
		addnewmedium.cpp \
		givemedium.cpp \
		changemedium.cpp \
		changeperson.cpp moc_mainwindow.cpp \
		moc_addnewperson.cpp \
		moc_addnewmedium.cpp \
		moc_givemedium.cpp \
		moc_changemedium.cpp \
		moc_changeperson.cpp
OBJECTS       = main.o \
		mainwindow.o \
		medium.o \
		book.o \
		cd.o \
		dvd.o \
		person.o \
		addnewperson.o \
		datamanager.o \
		addnewmedium.o \
		givemedium.o \
		changemedium.o \
		changeperson.o \
		moc_mainwindow.o \
		moc_addnewperson.o \
		moc_addnewmedium.o \
		moc_givemedium.o \
		moc_changemedium.o \
		moc_changeperson.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		beleg.pro
QMAKE_TARGET  = beleg
DESTDIR       = 
TARGET        = beleg

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_addnewperson.h ui_addnewmedium.h ui_givemedium.h ui_changemedium.h ui_changeperson.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: beleg.pro  /usr/share/qt4/mkspecs/default/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -o Makefile beleg.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile beleg.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/beleg1.0.0 || $(MKDIR) .tmp/beleg1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/beleg1.0.0/ && $(COPY_FILE) --parents mainwindow.h book.h medium.h cd.h dvd.h person.h addnewperson.h datamanager.h book.h addnewmedium.h givemedium.h changemedium.h changeperson.h .tmp/beleg1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp medium.cpp book.cpp cd.cpp dvd.cpp person.cpp addnewperson.cpp datamanager.cpp addnewmedium.cpp givemedium.cpp changemedium.cpp changeperson.cpp .tmp/beleg1.0.0/ && $(COPY_FILE) --parents mainwindow.ui addnewperson.ui addnewmedium.ui givemedium.ui changemedium.ui changeperson.ui .tmp/beleg1.0.0/ && (cd `dirname .tmp/beleg1.0.0` && $(TAR) beleg1.0.0.tar beleg1.0.0 && $(COMPRESS) beleg1.0.0.tar) && $(MOVE) `dirname .tmp/beleg1.0.0`/beleg1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/beleg1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_addnewperson.cpp moc_addnewmedium.cpp moc_givemedium.cpp moc_changemedium.cpp moc_changeperson.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_addnewperson.cpp moc_addnewmedium.cpp moc_givemedium.cpp moc_changemedium.cpp moc_changeperson.cpp
moc_mainwindow.cpp: person.h \
		medium.h \
		datamanager.h \
		book.h \
		cd.h \
		dvd.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_addnewperson.cpp: person.h \
		medium.h \
		mainwindow.h \
		datamanager.h \
		book.h \
		cd.h \
		dvd.h \
		addnewperson.h
	/usr/bin/moc $(DEFINES) $(INCPATH) addnewperson.h -o moc_addnewperson.cpp

moc_addnewmedium.cpp: medium.h \
		book.h \
		cd.h \
		dvd.h \
		addnewmedium.h
	/usr/bin/moc $(DEFINES) $(INCPATH) addnewmedium.h -o moc_addnewmedium.cpp

moc_givemedium.cpp: person.h \
		medium.h \
		givemedium.h
	/usr/bin/moc $(DEFINES) $(INCPATH) givemedium.h -o moc_givemedium.cpp

moc_changemedium.cpp: medium.h \
		changemedium.h
	/usr/bin/moc $(DEFINES) $(INCPATH) changemedium.h -o moc_changemedium.cpp

moc_changeperson.cpp: person.h \
		medium.h \
		changeperson.h
	/usr/bin/moc $(DEFINES) $(INCPATH) changeperson.h -o moc_changeperson.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_addnewperson.h ui_addnewmedium.h ui_givemedium.h ui_changemedium.h ui_changeperson.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_addnewperson.h ui_addnewmedium.h ui_givemedium.h ui_changemedium.h ui_changeperson.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_addnewperson.h: addnewperson.ui
	/usr/bin/uic addnewperson.ui -o ui_addnewperson.h

ui_addnewmedium.h: addnewmedium.ui
	/usr/bin/uic addnewmedium.ui -o ui_addnewmedium.h

ui_givemedium.h: givemedium.ui
	/usr/bin/uic givemedium.ui -o ui_givemedium.h

ui_changemedium.h: changemedium.ui
	/usr/bin/uic changemedium.ui -o ui_changemedium.h

ui_changeperson.h: changeperson.ui
	/usr/bin/uic changeperson.ui -o ui_changeperson.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		person.h \
		medium.h \
		datamanager.h \
		book.h \
		cd.h \
		dvd.h \
		addnewperson.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		person.h \
		medium.h \
		datamanager.h \
		book.h \
		cd.h \
		dvd.h \
		ui_mainwindow.h \
		addnewperson.h \
		addnewmedium.h \
		givemedium.h \
		changemedium.h \
		changeperson.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

medium.o: medium.cpp medium.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o medium.o medium.cpp

book.o: book.cpp book.h \
		medium.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o book.o book.cpp

cd.o: cd.cpp cd.h \
		medium.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cd.o cd.cpp

dvd.o: dvd.cpp dvd.h \
		cd.h \
		medium.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dvd.o dvd.cpp

person.o: person.cpp medium.h \
		person.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o person.o person.cpp

addnewperson.o: addnewperson.cpp ui_addnewperson.h \
		medium.h \
		addnewperson.h \
		person.h \
		mainwindow.h \
		datamanager.h \
		book.h \
		cd.h \
		dvd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addnewperson.o addnewperson.cpp

datamanager.o: datamanager.cpp medium.h \
		person.h \
		datamanager.h \
		book.h \
		cd.h \
		dvd.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datamanager.o datamanager.cpp

addnewmedium.o: addnewmedium.cpp addnewmedium.h \
		medium.h \
		book.h \
		cd.h \
		dvd.h \
		ui_addnewmedium.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addnewmedium.o addnewmedium.cpp

givemedium.o: givemedium.cpp givemedium.h \
		person.h \
		medium.h \
		ui_givemedium.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o givemedium.o givemedium.cpp

changemedium.o: changemedium.cpp changemedium.h \
		medium.h \
		ui_changemedium.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o changemedium.o changemedium.cpp

changeperson.o: changeperson.cpp changeperson.h \
		person.h \
		medium.h \
		ui_changeperson.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o changeperson.o changeperson.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_addnewperson.o: moc_addnewperson.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addnewperson.o moc_addnewperson.cpp

moc_addnewmedium.o: moc_addnewmedium.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addnewmedium.o moc_addnewmedium.cpp

moc_givemedium.o: moc_givemedium.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_givemedium.o moc_givemedium.cpp

moc_changemedium.o: moc_changemedium.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_changemedium.o moc_changemedium.cpp

moc_changeperson.o: moc_changeperson.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_changeperson.o moc_changeperson.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

